spring:
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    enabled: true
    encoding: UTF-8
#logging:
#  level:
#    root: debug
